apply plugin: 'com.android.application'

//
// build.gradle in TeamCode
//

apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'

android {
    namespace = 'org.firstinspires.ftc.teamcode'

    packagingOptions {
        jniLibs {
            pickFirsts += ['**/*.so']
        }
        jniLibs.useLegacyPackaging true
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.pedropathing.com' }
}

dependencies {
    implementation project(':FtcRobotController')
    implementation 'com.google.mlkit:pose-detection-common:17.0.0'

    // Pedro Pathing
    implementation 'com.pedropathing:ftc:2.1.2'
    implementation 'com.pedropathing:telemetry:1.0.0'
}